apiVersion: 1

datasources:
  - name: InfluxDB3 (Load)
    uid: influxdb3_load
    type: influxdb
    access: proxy
    url: http://localhost:8181
    basicAuth: true
    isDefault: true
    jsonData:
      version: InfluxQL
      dbName: load              
      httpMode: POST
      httpHeaderName1: "Authorization"
    secureJsonData:
      httpHeaderValue1: "Token apiv3_9rdZKWDNT9DcuIli9W6R9ePr9KpeRXTkWMktG_1B5r504DRNMsYviUUz5107Hq1K9C4xmIvJDo7YayM1nd_Wsg"